version: "3.8"
services:
  invoice:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: invoice_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
